/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.BorderLayout;
import java.awt.Color;

import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.border.Border;

/**
 *
 * @author kumul
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();

        sellPanel venta = new sellPanel();
        venta.setSize(1300, 674);
        venta.setLocation(0, 0);

        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(venta, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customBtn = new javax.swing.JPanel();
        customBtnTxt = new javax.swing.JLabel();
        customBtn2 = new javax.swing.JPanel();
        customBtnTxt1 = new javax.swing.JLabel();
        customBtn3 = new javax.swing.JPanel();
        customBtnTxt2 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        tittleBar = new javax.swing.JPanel();
        menuTxt = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        userImg = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        menuBtn = new javax.swing.JPanel();
        menuImg = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        customBtn.setBackground(new java.awt.Color(133, 146, 173));
        customBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customBtnMouseExited(evt);
            }
        });

        customBtnTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        customBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customBtnTxt.setText("Facturar");

        javax.swing.GroupLayout customBtnLayout = new javax.swing.GroupLayout(customBtn);
        customBtn.setLayout(customBtnLayout);
        customBtnLayout.setHorizontalGroup(
            customBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        customBtnLayout.setVerticalGroup(
            customBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        customBtn2.setBackground(new java.awt.Color(133, 146, 173));
        customBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customBtn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customBtn2MouseExited(evt);
            }
        });

        customBtnTxt1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customBtnTxt1.setForeground(new java.awt.Color(255, 255, 255));
        customBtnTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customBtnTxt1.setText("Inventario");

        javax.swing.GroupLayout customBtn2Layout = new javax.swing.GroupLayout(customBtn2);
        customBtn2.setLayout(customBtn2Layout);
        customBtn2Layout.setHorizontalGroup(
            customBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customBtnTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        customBtn2Layout.setVerticalGroup(
            customBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customBtnTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        customBtn3.setBackground(new java.awt.Color(133, 146, 173));
        customBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customBtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customBtn3MouseExited(evt);
            }
        });

        customBtnTxt2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customBtnTxt2.setForeground(new java.awt.Color(255, 255, 255));
        customBtnTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customBtnTxt2.setText("Usuarios");

        javax.swing.GroupLayout customBtn3Layout = new javax.swing.GroupLayout(customBtn3);
        customBtn3.setLayout(customBtn3Layout);
        customBtn3Layout.setHorizontalGroup(
            customBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customBtnTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        customBtn3Layout.setVerticalGroup(
            customBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customBtnTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 730));
        setSize(new java.awt.Dimension(1400, 730));

        tittleBar.setBackground(new java.awt.Color(0, 177, 157));

        menuTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuTxt.setForeground(new java.awt.Color(255, 255, 255));
        menuTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuTxt.setText("{Page}");

        userPanel.setBackground(new java.awt.Color(255, 255, 255));
        userPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 177, 157), 4, true));

        userImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userImg.setText("{img}");

        userName.setText("{userName}");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userImg, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menuBtn.setBackground(new java.awt.Color(0, 177, 157));
        menuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuBtnMouseExited(evt);
            }
        });

        menuImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuImg.setText("X");

        javax.swing.GroupLayout menuBtnLayout = new javax.swing.GroupLayout(menuBtn);
        menuBtn.setLayout(menuBtnLayout);
        menuBtnLayout.setHorizontalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuImg, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuBtnLayout.setVerticalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuImg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout tittleBarLayout = new javax.swing.GroupLayout(tittleBar);
        tittleBar.setLayout(tittleBarLayout);
        tittleBarLayout.setHorizontalGroup(
            tittleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tittleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 903, Short.MAX_VALUE)
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        tittleBarLayout.setVerticalGroup(
            tittleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tittleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tittleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        content.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tittleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(tittleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMouseEntered
        menuBtn.setBackground(new Color(0,191,168));
    }//GEN-LAST:event_menuBtnMouseEntered

    private void menuBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMouseExited
        menuBtn.setBackground(new Color(0,177,157));
    }//GEN-LAST:event_menuBtnMouseExited

    private void menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMouseClicked
        // Creamos un menú desplegable
        JPopupMenu popupMenu = new JPopupMenu();
        // Agregamos elementos al menú desplegable
        popupMenu.add(customBtn);
        popupMenu.add(customBtn2);
        popupMenu.add(customBtn3);
        // Mostramos el menú desplegable en la posición del botón
        popupMenu.show(menuBtn, 0, menuBtn.getHeight());
    }//GEN-LAST:event_menuBtnMouseClicked

    private void customBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customBtnMouseEntered
        customBtn.setBackground(new Color(158,169,190));
    }//GEN-LAST:event_customBtnMouseEntered

    private void customBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customBtnMouseExited
        customBtn.setBackground(new Color(133,146,173));
    }//GEN-LAST:event_customBtnMouseExited

    private void customBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customBtn2MouseEntered
        customBtn2.setBackground(new Color(158,169,190));
    }//GEN-LAST:event_customBtn2MouseEntered

    private void customBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customBtn2MouseExited
        customBtn2.setBackground(new Color(133,146,173));
    }//GEN-LAST:event_customBtn2MouseExited

    private void customBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customBtn3MouseEntered
        customBtn3.setBackground(new Color(158,169,190));
    }//GEN-LAST:event_customBtn3MouseEntered

    private void customBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customBtn3MouseExited
        customBtn3.setBackground(new Color(133,146,173));
    }//GEN-LAST:event_customBtn3MouseExited

    private void customBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customBtnMouseClicked
        sellPanel venta = new sellPanel();
        venta.setSize(1300, 674);
        venta.setLocation(0, 0);

        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(venta, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_customBtnMouseClicked

    private void customBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customBtn2MouseClicked
        Inventario inventario = new Inventario();
        System.out.println("Hola");
        inventario.setSize(1300, 674);
        inventario.setLocation(0,0);

        content.removeAll();
        content.setLayout(new BorderLayout());
        content.add(inventario, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_customBtn2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel content;
    private javax.swing.JPanel customBtn;
    private javax.swing.JPanel customBtn2;
    private javax.swing.JPanel customBtn3;
    private javax.swing.JLabel customBtnTxt;
    private javax.swing.JLabel customBtnTxt1;
    private javax.swing.JLabel customBtnTxt2;
    private javax.swing.JPanel menuBtn;
    private javax.swing.JLabel menuImg;
    private javax.swing.JLabel menuTxt;
    private javax.swing.JPanel tittleBar;
    private javax.swing.JLabel userImg;
    private javax.swing.JLabel userName;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
