/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.vista;

import main.java.aplicacion.Aplicacion;
import main.java.modelo.Producto;
import main.java.modelo.ProductoAlimento;
import main.java.modelo.ProductoElectronico;
import main.java.modelo.Proveedor;
import main.java.modelo.RWProductos;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

/**
 *
 * @author Jorge Olvera
 */
public class addProduct extends javax.swing.JFrame {
    private int opc;
    private int index;
    private Producto producto;
    /**
     * Creates new form addProduct
     */
    private String[] tipo = {"Electronico","Alimento"};
    public addProduct() {
        initComponents();
        this.opc = 1;
        
    }

    public addProduct(int index) {
        initComponents();
        this.index = index;
        this.opc = 2;
        replaceValors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabeliD = new javax.swing.JLabel();
        jLabelProveedor = new javax.swing.JLabel();
        jLabelAux = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtProvName = new javax.swing.JTextField();
        txtAux = new javax.swing.JTextField();
        cboTipo = new javax.swing.JComboBox<>();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        txtPovDireccion = new javax.swing.JTextField();
        txtProvContacto = new javax.swing.JTextField();
        jLabelProvName = new javax.swing.JLabel();
        jLabelProvDir = new javax.swing.JLabel();
        jLabelProvCont = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 255, 204));
        jLabelTitulo.setText("Datos generales");

        jLabelNombre.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelNombre.setText("Nombre del producto");

        jLabelDesc.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelDesc.setText("Descripcion");

        jLabelPrecio.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelPrecio.setText("Precio Unitario");

        jLabelCantidad.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelCantidad.setText("Cantidad");

        jLabeliD.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabeliD.setText("ID");

        jLabelProveedor.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelProveedor.setText("Proveedor");

        jLabelAux.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelAux.setText("Modelo");

        txtProvName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProvNameActionPerformed(evt);
            }
        });

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboTipoMouseClicked(evt);
            }
        });
        cboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoActionPerformed(evt);
            }
        });
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(tipo);
        cboTipo.setModel(comboModel);

        jButtonSave.setText("Guardar");
        jButtonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSaveMouseClicked(evt);
            }
        });
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonSave.setMnemonic(KeyEvent.VK_ENTER);
        getRootPane().setDefaultButton(jButtonSave);

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        jLabelProvName.setText("Nombre");

        jLabelProvDir.setText("Direccion");

        jLabelProvCont.setText("Contacto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAux, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAux, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelProvCont, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProvContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreP)
                            .addComponent(jLabelCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidad))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabeliD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtId)
                                .addComponent(jLabelDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrecio)
                                    .addComponent(jLabelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelProvName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProvName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelProvDir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPovDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButtonCancel))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelTitulo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelDesc)
                    .addComponent(jLabelPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreP)
                    .addComponent(txtPrecio)
                    .addComponent(txtDesc))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidad)
                    .addComponent(jLabeliD)
                    .addComponent(jLabelProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProvName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProvName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPovDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProvDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAux)
                    .addComponent(txtProvContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProvCont))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTipoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboTipoMouseClicked

    private void cboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoActionPerformed
        // TODO add your handling code here:
        actualizarInterfaz();
    }//GEN-LAST:event_cboTipoActionPerformed

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelMouseClicked

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveMouseClicked
        // TODO add your handling code here:
        String name = this.txtNombreP.getText();
        String desc = this.txtDesc.getText();
        double precio = Double.parseDouble(this.txtPrecio.getText());
        int cant = Integer.parseInt(this.txtCantidad.getText());
        String id = this.txtId.getText();
        String aux = this.txtAux.getText();

        String tipoProducto = tipo[cboTipo.getSelectedIndex()];
        
        if (this.opc == 1) {
            if (tipoProducto == "Electronico") {
                Aplicacion.listaProductos.add(new ProductoElectronico(aux, name, desc, precio, cant, id, new Proveedor(this.txtProvName.getText(), this.txtPovDireccion.getText(), this.txtProvContacto.getText())));
            } else if (tipoProducto == "Alimento") {
                Aplicacion.listaProductos.add(new ProductoAlimento(aux, name, desc, precio, cant, id, new Proveedor(this.txtProvName.getText(), this.txtPovDireccion.getText(), this.txtProvContacto.getText())));
            }
            //Se limpian los campos
            this.txtAux.setText("");
            this.txtDesc.setText("");
            this.txtNombreP.setText("");
            this.txtCantidad.setText("");
            this.txtId.setText("");
            this.txtPrecio.setText("");
            this.txtPovDireccion.setText("");
            this.txtProvContacto.setText("");
            this.txtProvName.setText("");
        } else {
            if (tipoProducto == "Electronico") {
                Aplicacion.listaProductos.set(index, new ProductoElectronico(aux, name, desc, precio, cant, id, new Proveedor(this.txtProvName.getText(), this.txtPovDireccion.getText(), this.txtProvContacto.getText())));
            } else if (tipoProducto == "Alimento") {
                Aplicacion.listaProductos.set(index, new ProductoAlimento(aux, name, desc, precio, cant, id, new Proveedor(this.txtProvName.getText(), this.txtPovDireccion.getText(), this.txtProvContacto.getText())));
            }
        }

        RWProductos.escribirDatos(Aplicacion.listaProductos);
        JOptionPane.showMessageDialog(this, "Datos guardados");
    }//GEN-LAST:event_jButtonSaveMouseClicked

    private void txtProvNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProvNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvNameActionPerformed
    private void actualizarInterfaz() {
        String tipoProducto = tipo[cboTipo.getSelectedIndex()];
        if (tipoProducto == "Electronico") {
            jLabelAux.setText("Modelo");
            txtAux.setText("");
        } else if (tipoProducto == "Alimento") {
            jLabelAux.setText("Fecha de Caducidad");
            txtAux.setText("");
        }
    }

    private void replaceValors(){
        this.producto = Aplicacion.listaProductos.get(index);
        if (this.producto instanceof ProductoAlimento) {
            ProductoAlimento productoAlimento = (ProductoAlimento)this.producto;
            this.cboTipo.setSelectedIndex(1);
            this.jLabelAux.setText("Fecha de Caducidad");
            this.txtAux.setText(productoAlimento.getFechaCaducidad());
        } else if (this.producto instanceof ProductoElectronico) {
            ProductoElectronico productoElectronico = (ProductoElectronico)this.producto;
            this.cboTipo.setSelectedIndex(0);
            this.jLabelAux.setText("Modelo");
            this.txtAux.setText(productoElectronico.getModelo());
        }
        this.txtDesc.setText(producto.getDescripcion());
        this.txtNombreP.setText(producto.getNombre());
        this.txtCantidad.setText(producto.getStock()+"");
        this.txtId.setText(producto.getCodigo());
        this.txtPrecio.setText(producto.getPrecio()+"");
        this.txtPovDireccion.setText(producto.getProveedor().getDireccion());
        this.txtProvContacto.setText(producto.getProveedor().getContacto());
        this.txtProvName.setText(producto.getProveedor().getNombre());
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelAux;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelProvCont;
    private javax.swing.JLabel jLabelProvDir;
    private javax.swing.JLabel jLabelProvName;
    private javax.swing.JLabel jLabelProveedor;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabeliD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAux;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtPovDireccion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProvContacto;
    private javax.swing.JTextField txtProvName;
    // End of variables declaration//GEN-END:variables
}
