package main.java.vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.Color;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.java.aplicacion.Aplicacion;
import main.java.controlador.SellPanelController;
import main.java.modelo.RWUsers;

/**
 *
 * @author kumul
 */
public class SellPanel extends javax.swing.JPanel {
    private SellPanelController controller;

    /**
     * Creates new form sellPanel
     */
    public SellPanel() {
        initComponents();
        controller = new SellPanelController(this, Aplicacion.listaProductos);
        replacePlaceholder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productsPanel = new javax.swing.JPanel();
        searchBar = new javax.swing.JPanel();
        searchProducts = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsGrid = new javax.swing.JPanel();
        ticketPanel = new javax.swing.JPanel();
        ticketBanner = new javax.swing.JPanel();
        ticketBannerTxt1 = new javax.swing.JLabel();
        newClientBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        showClientBanne = new javax.swing.JPanel();
        showClientTxt = new javax.swing.JLabel();
        sellPanel = new javax.swing.JPanel();
        sellBtn = new javax.swing.JPanel();
        sellTxt = new javax.swing.JLabel();
        showPrice = new javax.swing.JLabel();
        productsBar = new javax.swing.JPanel();
        displayNoProducts = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JPanel();
        cancelBtnTxt = new javax.swing.JLabel();
        selectedProductsList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setBackground(new java.awt.Color(244, 245, 251));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1300, 674));

        productsPanel.setBackground(new java.awt.Color(244, 245, 251));

        searchBar.setBackground(new java.awt.Color(244, 245, 251));

        searchProducts.setBackground(new java.awt.Color(255, 255, 255));
        searchProducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(154, 221, 217), 3, true));

        javax.swing.GroupLayout searchProductsLayout = new javax.swing.GroupLayout(searchProducts);
        searchProducts.setLayout(searchProductsLayout);
        searchProductsLayout.setHorizontalGroup(
            searchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        searchProductsLayout.setVerticalGroup(
            searchProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout searchBarLayout = new javax.swing.GroupLayout(searchBar);
        searchBar.setLayout(searchBarLayout);
        searchBarLayout.setHorizontalGroup(
            searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(searchProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchBarLayout.setVerticalGroup(
            searchBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        productsGrid.setBackground(new java.awt.Color(244, 245, 251));

        javax.swing.GroupLayout productsGridLayout = new javax.swing.GroupLayout(productsGrid);
        productsGrid.setLayout(productsGridLayout);
        productsGridLayout.setHorizontalGroup(
            productsGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        productsGridLayout.setVerticalGroup(
            productsGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(productsGrid);

        javax.swing.GroupLayout productsPanelLayout = new javax.swing.GroupLayout(productsPanel);
        productsPanel.setLayout(productsPanelLayout);
        productsPanelLayout.setHorizontalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1)
                .addGap(54, 54, 54))
        );
        productsPanelLayout.setVerticalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );

        ticketPanel.setBackground(new java.awt.Color(255, 255, 255));
        ticketPanel.setForeground(new java.awt.Color(255, 255, 255));

        ticketBanner.setBackground(new java.awt.Color(133, 146, 173));

        ticketBannerTxt1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ticketBannerTxt1.setForeground(new java.awt.Color(255, 255, 255));
        ticketBannerTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ticketBannerTxt1.setText("Ticket de venta");

        javax.swing.GroupLayout ticketBannerLayout = new javax.swing.GroupLayout(ticketBanner);
        ticketBanner.setLayout(ticketBannerLayout);
        ticketBannerLayout.setHorizontalGroup(
            ticketBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ticketBannerTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ticketBannerLayout.setVerticalGroup(
            ticketBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ticketBannerTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        newClientBtn.setBackground(new java.awt.Color(255, 255, 255));
        newClientBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newClientBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newClientBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newClientBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newClientBtnMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo");

        javax.swing.GroupLayout newClientBtnLayout = new javax.swing.GroupLayout(newClientBtn);
        newClientBtn.setLayout(newClientBtnLayout);
        newClientBtnLayout.setHorizontalGroup(
            newClientBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newClientBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );
        newClientBtnLayout.setVerticalGroup(
            newClientBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        showClientBanne.setBackground(new java.awt.Color(255, 255, 255));
        showClientBanne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        showClientTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showClientTxt.setText("Cliente {noClient}");
        showClientTxt.setAutoscrolls(true);
        showClientTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout showClientBanneLayout = new javax.swing.GroupLayout(showClientBanne);
        showClientBanne.setLayout(showClientBanneLayout);
        showClientBanneLayout.setHorizontalGroup(
            showClientBanneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showClientTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        showClientBanneLayout.setVerticalGroup(
            showClientBanneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showClientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        sellBtn.setBackground(new java.awt.Color(0, 177, 157));
        sellBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        sellBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sellBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sellBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sellBtnMouseExited(evt);
            }
        });

        sellTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sellTxt.setForeground(new java.awt.Color(255, 255, 255));
        sellTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sellTxt.setText("Vender");

        showPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showPrice.setForeground(new java.awt.Color(255, 255, 255));
        showPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showPrice.setText("${price}");

        javax.swing.GroupLayout sellBtnLayout = new javax.swing.GroupLayout(sellBtn);
        sellBtn.setLayout(sellBtnLayout);
        sellBtnLayout.setHorizontalGroup(
            sellBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellBtnLayout.createSequentialGroup()
                .addComponent(sellTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(showPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sellBtnLayout.setVerticalGroup(
            sellBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellBtnLayout.createSequentialGroup()
                .addGroup(sellBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(showPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(sellTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        productsBar.setBackground(new java.awt.Color(133, 146, 173));

        displayNoProducts.setBackground(new java.awt.Color(115, 114, 132));
        displayNoProducts.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        displayNoProducts.setForeground(new java.awt.Color(255, 255, 255));
        displayNoProducts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayNoProducts.setText("{noProducts} productos");
        displayNoProducts.setAlignmentY(2.0F);

        cancelBtn.setBackground(new java.awt.Color(133, 146, 173));
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtnMouseExited(evt);
            }
        });

        cancelBtnTxt.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cancelBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelBtnTxt.setText("Cancelar");
        cancelBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout cancelBtnLayout = new javax.swing.GroupLayout(cancelBtn);
        cancelBtn.setLayout(cancelBtnLayout);
        cancelBtnLayout.setHorizontalGroup(
            cancelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        cancelBtnLayout.setVerticalGroup(
            cancelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout productsBarLayout = new javax.swing.GroupLayout(productsBar);
        productsBar.setLayout(productsBarLayout);
        productsBarLayout.setHorizontalGroup(
            productsBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(displayNoProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        productsBarLayout.setVerticalGroup(
            productsBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productsBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(displayNoProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(productsBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sellPanelLayout = new javax.swing.GroupLayout(sellPanel);
        sellPanel.setLayout(sellPanelLayout);
        sellPanelLayout.setHorizontalGroup(
            sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(productsBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        sellPanelLayout.setVerticalGroup(
            sellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sellPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productsBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        selectedProductsList.setViewportView(jList1);

        javax.swing.GroupLayout ticketPanelLayout = new javax.swing.GroupLayout(ticketPanel);
        ticketPanel.setLayout(ticketPanelLayout);
        ticketPanelLayout.setHorizontalGroup(
            ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketPanelLayout.createSequentialGroup()
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(showClientBanne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newClientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sellPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ticketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ticketBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selectedProductsList, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ticketPanelLayout.setVerticalGroup(
            ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newClientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showClientBanne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedProductsList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(productsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ticketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sellBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellBtnMouseEntered
        sellBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_sellBtnMouseEntered

    private void sellBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellBtnMouseExited
        sellBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_sellBtnMouseExited

    private void newClientBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newClientBtnMouseEntered
        newClientBtn.setBackground(new Color(233,233,233));
    }//GEN-LAST:event_newClientBtnMouseEntered

    private void newClientBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newClientBtnMouseExited
        newClientBtn.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_newClientBtnMouseExited

    private void cancelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseEntered
        cancelBtn.setBackground(new Color(158,169,190));
    }//GEN-LAST:event_cancelBtnMouseEntered

    private void cancelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseExited
        cancelBtn.setBackground(new Color(133,146,173));
    }//GEN-LAST:event_cancelBtnMouseExited

    private void newClientBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newClientBtnMouseClicked
        controller.clearSelectedProducts();
    }//GEN-LAST:event_newClientBtnMouseClicked

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        int option = JOptionPane.showConfirmDialog(productsPanel, "¿Estás seguro que quieres vaciar la lista de articulos seleccionados?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            controller.clearSelectedProducts();   
        }
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void sellBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellBtnMouseClicked
        controller.sellSelectProducts();
    }//GEN-LAST:event_sellBtnMouseClicked
    
    public void setSelectedList(DefaultListModel<SelectedProduct> selectedListModel){
        this.jList1 = new JList<SelectedProduct>(selectedListModel);
    }
    
    public JList<SelectedProduct> getjList1() {
        return jList1;
    }

    private void replacePlaceholder(){
        showClientTxt.setText("Cliente "+Aplicacion.tienda.getNoClients());
        //menuImg.setIcon(new ImageIcon("src/resources/images/menu2.png"));
        showPrice.setText("0.0");
        displayNoProducts.setText("0 producto(s)");
    }

    public void updateFinalPrice(double finalPrice){
        showPrice.setText(finalPrice+"");
    }
    public void updateNoProducts(int noProducts){
        displayNoProducts.setText(noProducts+" producto(s)");
    }
    public void updateNoclients(int noClient){
        showClientTxt.setText("Cliente "+noClient);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancelBtn;
    private javax.swing.JLabel cancelBtnTxt;
    private javax.swing.JLabel displayNoProducts;
    private javax.swing.JLabel jLabel1;
    private JList<SelectedProduct> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel newClientBtn;
    private javax.swing.JPanel productsBar;
    public javax.swing.JPanel productsGrid;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JPanel searchBar;
    private javax.swing.JPanel searchProducts;
    private javax.swing.JScrollPane selectedProductsList;
    private javax.swing.JPanel sellBtn;
    private javax.swing.JPanel sellPanel;
    private javax.swing.JLabel sellTxt;
    private javax.swing.JPanel showClientBanne;
    private javax.swing.JLabel showClientTxt;
    private javax.swing.JLabel showPrice;
    private javax.swing.JPanel ticketBanner;
    private javax.swing.JLabel ticketBannerTxt1;
    private javax.swing.JPanel ticketPanel;
    // End of variables declaration//GEN-END:variables
}
